import Head from "next/head";
import Image from "next/image";
import { Roboto } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { getSession } from "next-auth/react";
//import { useEffect, useState } from "react";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export default function Home({user}) {
  console.log(user);
  // const [user, setUser] = useState(null)

  // useEffect(() => {
  //   (async()=>{
  //     const session = await getSession()
  //     console.log(session)
  //     setUser(session.user)
  //   })()
  // }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={roboto.className}>
          <h1>Hola Tomas!</h1>
            {user && 
              <>
                <h3>{user.name}</h3>
                {user.email && <p>{user.email}</p>}
                <Image src={user.image} alt={`Imagen de ${user.name}`} height='200' width='200' priority />
              </>
            }
      </main>
    </>
  );
}


export const getServerSideProps = async (context) => {
  const session = await getSession(context)
  return {
    props: { user: session.user },
}}